apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: products
spec:
  selector:
    app: products-microservice
  ports:
    - port: 80
      targetPort: 5050
  type: LoadBalancer