apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
spec:
  selector:
    app: payment-microservice
  ports:
    - port: 80
      targetPort: 5050
  type: LoadBalancer