apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: products
spec:
  selector:
    app: products-microservice
  ports:
    - port: 80
      targetPort: 5050
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: products-service-clusterip
#   namespace: products
# spec:
#   selector:
#     app: products-microservice
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5050
#   type: ClusterIP